owner: hahow # Your GitHub username
repo: hahow-for-business-upptime # Your Github repository name

# Add your sites here
sites:
  - name: Hahow for Business Home
    url: https://business.hahow.in
  - name: Hahow for Business Health
    url: https://hahow.business.hahow.in/health
assignees: # Users to assign downtime issues (optional)
  - citysite102

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /hahow-for-business-upptime
  logoUrl: https://raw.githubusercontent.com/hahow/hahow-for-business-upptime/master/static/img/icon.svg
  name: Hahow for Business
  navbar:
    - title: Status
      href: /hahow-for-business-upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
