owner: hahow # Your GitHub username
repo: hahow-for-business-upptime # Your Github repository name

# Add your sites here
sites:
  - name: Hahow for Business Health
    url: https://business.hahow.in/health
  - name: Test Broken Site 4
    url: https://thissitedoesnotexist4.com
assignees: # Users to assign downtime issues (optional)
  - hrs113355
  - RongRongTeng
  - qoosuperman
  - LanceRabbit
  - amowu

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /hahow-for-business-upptime
  logoUrl: https://raw.githubusercontent.com/hahow/hahow-for-business-upptime/master/static/img/icon.svg
  name: Hahow for Business
  navbar:
    - title: Status
      href: /hahow-for-business-upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
workflowSchedule:
  uptime: "*/15 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
